[package]
name = "viri"
version = "0.1.0"
authors = ["sharnoff <github@max.sharnoff.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3"
clap = { version = "2.33", features = ["yaml"] }
# crossterm = { version = "0.16", features = ["serde"] }
crossterm = { git = "https://github.com/sharnoff/crossterm.git", features = ["serde"] }
lazy_static = "1.4"
libc = "0.2"
lock_api = "0.3"
log = { version = "0.4", features = ["serde"] }
parking_lot = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
uuid = { version = "0.8", features = ["v4"] }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
lto = true
