[package]
name = "viri"
version = "0.1.0"
authors = ["sharnoff <github@max.sharnoff.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
backtrace = "0.3"
clap = { version = "2.33", features = ["yaml"] }
crossterm = { version = "^0.17.6", features = ["serde"] }
lazy_static = "1.4"
libc = "0.2"
lock_api = "0.3"
log = { version = "0.4", features = ["serde"] }
parking_lot = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
unicode-width = "0.1.7"
uuid = { version = "0.8", features = ["v4"] }
# Syntect comes with many things turned on by default - we don't need all of those,
# so we manually include the few things that we *do* need
syntect = { version = "4.2.0", features = ["regex-onig", "parsing"] }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
lto = true
